import axios from 'axios';
import { ModelType, MessageType, PdfImageMeta } from '../types';
import { ttsService } from './ttsService';
import { isElectron } from './electronApi';
import { tokenCountingService } from './tokenCountingService';

/**
 * Render the AI-generated descriptions of PDF figures into a markdown-style
 * block we can append to the user message content. This is what makes the
 * descriptions actually reach the LLM on every turn (even if the user later
 * switches to a text-only model). We label items by page + caption-label
 * when we have one, so the LLM can cross-reference with the document's own
 * "Fig. 1", "Table 2" references.
 *
 * Output looks like:
 *
 *   --- Figures in "paper.pdf" (described by gemma3:latest) ---
 *   • Figure 1 (page 2): The figure compares three protein-LM architectures…
 *   • Figure 2 (page 4): A line chart with x-axis "epoch" 0–50…
 *   • Table 1 (page 3): A 6x9 comparison table contrasting SWING vs five baselines…
 *   ---
 *
 * Items without a `description` are still listed (with their caption and
 * page) so the LLM at least knows the figure exists. Items missing both
 * `description` AND `caption` are skipped — they'd add zero information.
 */
export const formatPdfImageMetaForLlm = (
  pdfName: string,
  metas: PdfImageMeta[],
): string => {
  if (!Array.isArray(metas) || metas.length === 0) return '';
  const usefulMetas = metas.filter(
    (m) => (m && (m.description || m.caption))
  );
  if (usefulMetas.length === 0) return '';
  // If any of the items has a `describedBy`, surface that model name in the
  // header so the receiving LLM knows where these descriptions came from.
  const describers = Array.from(
    new Set(
      usefulMetas
        .map((m) => m.describedBy)
        .filter((s): s is string => !!s)
    )
  );
  const headerSuffix = describers.length > 0
    ? ` (figure descriptions generated by ${describers.join(', ')})`
    : '';
  const lines: string[] = [];
  lines.push(`\n\n--- Figures in "${pdfName}"${headerSuffix} ---`);
  for (const m of usefulMetas) {
    const head = m.label
      ? `${m.label} (page ${m.page})`
      : `Figure ${m.index} (page ${m.page})`;
    const captionPart = m.caption ? ` — caption: "${m.caption}"` : '';
    if (m.description) {
      lines.push(`• ${head}${captionPart}\n   ${m.description.replace(/\n+/g, ' ')}`);
    } else {
      // No AI description was produced (e.g. text-only current model at
      // extraction time, or the describer failed). At minimum convey the
      // caption + label so the main LLM doesn't think the figure is empty.
      lines.push(`• ${head}${captionPart}\n   (no visual description available)`);
    }
  }
  lines.push('---');
  return lines.join('\n');
};


// Function to get the base URL, checking localStorage first
const getBaseURL = (): string => {
  // Check if user has set a custom Ollama API URL
  const customUrl = localStorage.getItem('ollamaApiUrl');
  if (customUrl && customUrl.trim() !== '') {
    // Custom URL is already normalized with /api appended
    console.log(`Using custom Ollama URL from settings: ${customUrl.trim()}`);
    return customUrl.trim();
  }
  
  // Electron app: Direct connection to Ollama
  if (isElectron()) {
    const ollamaUrl = process.env.REACT_APP_OLLAMA_URL || 'http://localhost:11434';
    console.log(`[Electron] Using direct Ollama URL: ${ollamaUrl}/api`);
    return `${ollamaUrl}/api`;
  }
  
  // Browser/Docker: Use nginx proxy (respects runtime OLLAMA_URL env var)
  console.log('[Browser/Docker] Using nginx proxy: /api/ollama');
  return '/api/ollama';
};

// Function to get the API key from localStorage
const getApiKey = (): string => {
  return localStorage.getItem('ollamaApiKey') || '';
};

// Function to get headers with optional API key
const getHeaders = (): Record<string, string> => {
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
  };
  
  const apiKey = getApiKey();
  if (apiKey && apiKey.trim() !== '') {
    headers['Authorization'] = `Bearer ${apiKey.trim()}`;
  }
  
  return headers;
};

// Get the initial base URL
let baseURL = getBaseURL();

// Export function to get Ollama base URL (without /api suffix)
export const getOllamaBaseUrl = (): string => {
  // Check if user has set a custom Ollama API URL
  const customUrl = localStorage.getItem('ollamaApiUrl');
  if (customUrl && customUrl.trim() !== '') {
    // Remove /api suffix if present
    const url = customUrl.trim();
    return url.endsWith('/api') ? url.slice(0, -4) : url;
  }
  
  // Electron app: Direct connection to Ollama
  if (isElectron()) {
    const ollamaUrl = process.env.REACT_APP_OLLAMA_URL || 'http://localhost:11434';
    return ollamaUrl;
  }
  
  // Browser/Docker: Use nginx proxy
  return '/api/ollama';
};

const api = axios.create({
  baseURL,
  headers: {
    'Content-Type': 'application/json',
  },
});

// Function to update the base URL dynamically
export const updateBaseURL = (newUrl?: string): void => {
  baseURL = newUrl || getBaseURL();
  api.defaults.baseURL = baseURL;
};

// Fetch available models
export const fetchModels = async (): Promise<ModelType[]> => {
  try {
    const endpoint = '/tags';
    const response = await api.get(endpoint, {
      headers: getHeaders(),
    });
    
if (response.data && response.data.models) {
      // Filter out embedding models (nomic, embed) - these are not for chat
      const chatModels = response.data.models.filter((model: any) => {
        const modelName = model.name.toLowerCase();
        return !modelName.includes('nomic') && !modelName.includes('embed');
      });
      
      return chatModels.map((model: any) => ({
        id: model.name,
        name: model.name,
        size: model.size,
        quantization: model.name.includes('q') ? model.name.split('-').pop() : undefined,
        isDefault: false,
      }));
    }
    
    // Return empty array when API is not available
    return [];
  } catch (error) {
    console.error('Error fetching models:', error);
    
    // Return empty array when there's an error
    return [];
  }
};

// Variable to store the current reader for cancellation
let currentReader: ReadableStreamDefaultReader<Uint8Array> | null = null;

// Function to cancel the current stream
// Returns true if successfully cancelled, false otherwise
export const cancelStream = async (): Promise<boolean> => {
  if (currentReader) {
    try {
      await currentReader.cancel('User cancelled the response');
      currentReader = null;
      return true;
    } catch (error) {
      console.error('Error cancelling stream:', error);
      return false;
    }
  }
  return true; // No active reader to cancel, so return true
};

// Helper function to filter out chain-of-thought reasoning (text starting with asterisk)
const filterThinkingText = (text: string): string => {
  // Remove text starting with asterisk at the beginning of responses
  // Pattern 1: *...* (both asterisks) followed by actual response
  // Pattern 2: *...punctuation...CapitalLetter (thinking ends with punctuation/ellipsis before actual response)
  
  // First try to remove text wrapped in asterisks followed by whitespace
  let filtered = text.replace(/^\*[^*]+\*\s+/g, '');
  
  // If that didn't work, try to remove thinking text that starts with * but doesn't end with *
  if (filtered === text && text.startsWith('*')) {
    // Look for patterns like:
    // "*thinking text about...Hello!" -> keep "Hello!"
    // "*thinking text.Hello!" -> keep "Hello!"
    // Match from * until we find punctuation followed by capital letter starting a sentence
    filtered = text.replace(/^\*.*?[.!?…]+(?=[A-Z][a-z])/, '');
    
    // If still no match, try the original pattern (lowercase followed by capital)
    if (filtered === text) {
      filtered = text.replace(/^\*.*?[a-z](?=[A-Z][a-z])/, '');
    }
  }
  
  return filtered.trim();
};

// Send a message to the model and get a response
export const sendMessage = async (
  modelId: string,
  messages: MessageType[],
  options?: Record<string, any>,
  onStreamUpdate?: (chunk: string, responseData?: any) => void,
  isListening?: boolean
): Promise<{response: string, tokensSent: number, tokensReceived: number}> => {
  // Initialize token counting variables outside try block for proper scope
  let tokensSent = 0;

  // GPU/CPU layer placement is left entirely to Ollama. We deliberately do
  // NOT send num_gpu — Ollama auto-detects how many layers fit in dedicated
  // VRAM and keeps the overflow on the CPU. Forcing a layer count made large
  // models spill into shared GPU memory (system RAM over PCIe), which loads
  // and runs far slower than Ollama's own placement.
  // Build the effective options once, shared by both streaming and non-streaming paths.
  const effectiveOptions: Record<string, any> = {
    ...(options || { num_ctx: 4096, temperature: 0.8 }),
  };

  try {
    // Extract image attachments and text attachments
    const imageAttachments: string[] = [];
    
      // Process messages to include file attachments
    const formattedMessages = messages.map(msg => {
      // If the message has attachments, handle them appropriately
      if (msg.attachments && msg.attachments.length > 0) {
        // Create a new content string that includes the text file content
        let enhancedContent = msg.content;
        // Array to hold image attachments for this specific message
        const messageImages: string[] = [];
        
    // Process each attachment
    msg.attachments.forEach(attachment => {
      // Handle text and PDF attachments by including their content in the message
      if ((attachment.type === 'text' || attachment.type === 'pdf') && attachment.content) {
        enhancedContent += `\n\n--- File: ${attachment.name} ---\n${attachment.content}\n---\n`;
      }

      // For PDFs, ALSO append any AI-generated descriptions of figures
      // (produced at extraction time by a vision model). This gives even a
      // text-only LLM a reliable, persistent textual rendering of every
      // figure in the document on every subsequent turn.
      if (attachment.type === 'pdf' && Array.isArray(attachment.imageMeta) && attachment.imageMeta.length > 0) {
        enhancedContent += formatPdfImageMetaForLlm(attachment.name, attachment.imageMeta);
      }

      // Collect image attachments for this message
      if (attachment.type === 'image' && attachment.content) {
        // Extract base64 data from data URL (remove the prefix like "data:image/jpeg;base64,")
        const base64Data = attachment.content.split(',')[1];
        if (base64Data) {
          messageImages.push(base64Data);
          // Also add to the global array for logging purposes
          imageAttachments.push(base64Data);
        }
      }

      // PDF attachments may carry extracted images (embedded raster images and
      // rendered page previews for charts/diagrams) — forward them to Ollama
      // as additional `images` so vision models can actually "see" the PDF.
      if (attachment.type === 'pdf' && attachment.images && attachment.images.length > 0) {
        for (const b64 of attachment.images) {
          if (!b64) continue;
          // Backend already returns raw base64 (no data: prefix), but be defensive.
          const clean = b64.includes(',') ? b64.split(',')[1] : b64;
          if (clean) {
            messageImages.push(clean);
            imageAttachments.push(clean);
          }
        }
      }
    });

        
        // Return message with images included in the message object per Ollama API docs
        return {
          role: msg.role,
          content: enhancedContent,
          // Only include images field if there are images
          ...(messageImages.length > 0 && { images: messageImages })
        };
      }
      
      // If no attachments, just return the original message
      return {
        role: msg.role,
        content: msg.content,
      };
    });

    // Check if both full voice mode is enabled AND microphone is listening to add system message
    const ttsSettings = ttsService.getSettings();
    let systemMessage: any = null;
    let systemMessageTokens = 0;
    
    // Add system message when BOTH full voice mode is enabled AND microphone is listening
    if (ttsSettings.fullVoiceMode && isListening) {
      systemMessage = {
        role: 'system' as const,
        content: 'You are a helpful and conversational assistant. Maintain context across turns and speak naturally as if in an ongoing dialogue.'
      };
      
      // Count tokens in system message for truncation calculation
      systemMessageTokens = tokenCountingService.countTokens(systemMessage.content) + 10; // +10 for overhead
    }

    // Get context length from options
    const contextLength = options?.num_ctx || 4096;
    
    // Log token usage before truncation
    console.log('📊 Pre-truncation token analysis:');
    console.log(tokenCountingService.getTokenUsageSummary(messages, contextLength));
    
    // Check if we need to truncate messages to fit context length
    let truncatedMessages = messages;
    if (tokenCountingService.exceedsContextLength(messages, contextLength)) {
      console.log('⚠️ Messages exceed context length, applying truncation...');
      truncatedMessages = tokenCountingService.truncateMessagesToFitContext(
        messages, // Use original messages for better truncation decisions
        contextLength,
        systemMessageTokens
      );
      
      console.log('✅ Post-truncation token analysis:');
      console.log(tokenCountingService.getTokenUsageSummary(truncatedMessages, contextLength));
    }
    
    // Now format the (possibly truncated) messages for the API
    const messagesToSend = truncatedMessages.map(msg => {
      // If the message has attachments, handle them appropriately
      if (msg.attachments && msg.attachments.length > 0) {
        // Create a new content string that includes the text file content
        let enhancedContent = msg.content;
        // Array to hold image attachments for this specific message
        const messageImages: string[] = [];
        
        // Process each attachment
        msg.attachments.forEach(attachment => {
          // Handle text and PDF attachments by including their content in the message
          if ((attachment.type === 'text' || attachment.type === 'pdf') && attachment.content) {
            enhancedContent += `\n\n--- File: ${attachment.name} ---\n${attachment.content}\n---\n`;
          }

          // For PDFs, inline AI-generated descriptions of figures so even a
          // text-only LLM sees what each figure shows. See formatPdfImageMetaForLlm.
          if (attachment.type === 'pdf' && Array.isArray(attachment.imageMeta) && attachment.imageMeta.length > 0) {
            enhancedContent += formatPdfImageMetaForLlm(attachment.name, attachment.imageMeta);
          }

          // Collect image attachments for this message
          if (attachment.type === 'image' && attachment.content) {
            // Extract base64 data from data URL (remove the prefix like "data:image/jpeg;base64,")
            const base64Data = attachment.content.split(',')[1];
            if (base64Data) {
              messageImages.push(base64Data);
              // Also add to the global array for logging purposes
              imageAttachments.push(base64Data);
            }
          }

          // PDF attachments may carry extracted images (embedded raster images
          // and rendered page previews for charts/diagrams). Forward them to
          // Ollama as additional `images` so vision models can "see" the PDF.
          if (attachment.type === 'pdf' && attachment.images && attachment.images.length > 0) {
            for (const b64 of attachment.images) {
              if (!b64) continue;
              // Backend returns raw base64 (no data: prefix), but be defensive.
              const clean = b64.includes(',') ? b64.split(',')[1] : b64;
              if (clean) {
                messageImages.push(clean);
                imageAttachments.push(clean);
              }
            }
          }
        });

          
        // Return message with images included in the message object per Ollama API docs
        return {
          role: msg.role,
          content: enhancedContent,
          // Only include images field if there are images
          ...(messageImages.length > 0 && { images: messageImages })
        };
      }
      
      // If no attachments, just return the original message
      return {
        role: msg.role,
        content: msg.content,
      };
    });
    
    // Prepare final messages with system message if needed
    let finalMessages = messagesToSend;
    if (systemMessage) {
      // Insert system message at the beginning if it's not already there
      const hasSystemMessage = finalMessages.some(msg => msg.role === 'system');
      if (!hasSystemMessage) {
        finalMessages = [systemMessage, ...messagesToSend];
      }
    }

    // Calculate tokens sent (after truncation and formatting)
    let tokensSent = tokenCountingService.countTotalTokens(truncatedMessages) + systemMessageTokens;
    console.log(`📤 Tokens sent to LLM: ${tokensSent}`);
  
    
const endpoint = '/chat';
    
    // Log the full URL being used
    
    // Heuristic detector for Ollama errors that mean "this model can't
    // handle the number of images you sent". We DON'T hardcode model
    // names — we react to what the server actually says. Examples seen:
    //   "this model only supports one image while more than one image requested"
    //   "model only supports a single image"
    //   "too many images"
    // If any of these appear in the error body, we transparently retry
    // with at most one image per message (keeping the first one).
    const isTooManyImagesError = (body: string): boolean => {
      if (!body) return false;
      const b = body.toLowerCase();
      return (
        (b.includes('image') && (b.includes('only support') || b.includes('only one') || b.includes('single image') || b.includes('one image'))) ||
        b.includes('too many images') ||
        (b.includes('more than one image') && b.includes('image'))
      );
    };

    // Build a variant of `finalMessages` with images per message capped.
    // `cap = 0` removes the `images` field entirely (text-only retry).
    const capMessageImages = (msgs: any[], cap: number): any[] => {
      return msgs.map(m => {
        if (!m || !Array.isArray(m.images) || m.images.length === 0) return m;
        if (cap <= 0) {
          const { images, ...rest } = m;
          return rest;
        }
        if (m.images.length <= cap) return m;
        return { ...m, images: m.images.slice(0, cap) };
      });
    };

    // If streaming is enabled and callback is provided
    if (onStreamUpdate) {
      // Build the request payload. We may retry with fewer images, so
      // we wrap the fetch in a small loop that reacts to Ollama's actual
      // error body (no hardcoded model names).
      const buildPayload = (msgs: any[]): any => ({
        model: modelId,
        messages: msgs,
        stream: true,
        keep_alive: -1, // Keep model loaded in RAM indefinitely
        options: effectiveOptions, // GPU/CPU split left entirely to Ollama
      });

      // We try up to 3 progressions: original images → 1 image per msg → 0 images.
      // Each step is only taken if the server explicitly complained about
      // image count. Any other error is re-thrown immediately.
      const imageCaps: Array<number | null> = [null, 1, 0]; // null = no cap
      let response: Response | null = null;
      let attempt = 0;
      let lastErrorBody = '';

      for (; attempt < imageCaps.length; attempt++) {
        const cap = imageCaps[attempt];
        const msgsForAttempt =
          cap === null ? finalMessages : capMessageImages(finalMessages, cap);

        if (attempt > 0) {
          console.warn(
            `↻ Retrying /api/chat with images capped at ${cap === 0 ? 'none' : cap} ` +
            `per message (server said: ${lastErrorBody.slice(0, 200)})`,
          );
        }

        response = await fetch(`${baseURL}${endpoint}`, {
          method: 'POST',
          headers: getHeaders(),
          body: JSON.stringify(buildPayload(msgsForAttempt)),
        });

        if (response.ok) break;

        // Read the server's error body so we can both log it and decide
        // whether retrying makes sense.
        let serverDetail = '';
        try {
          serverDetail = await response.text();
        } catch {
          /* ignore */
        }
        lastErrorBody = serverDetail;

        console.error(
          `Ollama /api/chat returned ${response.status}.`,
          serverDetail ? `Server said: ${serverDetail}` : '(no body)',
        );

        // Only retry on the specific "too many images" family of errors,
        // and only if we still have a stricter cap to try.
        const hasMoreRetries = attempt < imageCaps.length - 1;
        if (!hasMoreRetries || !isTooManyImagesError(serverDetail)) {
          throw new Error(
            `HTTP error! status: ${response.status}${
              serverDetail ? ` — ${serverDetail.slice(0, 500)}` : ''
            }`,
          );
        }
        // else loop & retry with stricter image cap
      }

      if (!response || !response.ok) {
        throw new Error(
          `HTTP error! status: ${response?.status ?? 'unknown'}${
            lastErrorBody ? ` — ${lastErrorBody.slice(0, 500)}` : ''
          }`,
        );
      }


      
      if (!response.body) {
        throw new Error('Response body is null');
      }
      
      // Store the reader globally so it can be cancelled
      currentReader = response.body.getReader();
      const decoder = new TextDecoder();
      let fullResponse = '';
      
      try {
        while (true) {
          const { done, value } = await currentReader.read();
          
          if (done) {
            break;
          }
          
          // Decode the chunk
          const chunk = decoder.decode(value, { stream: true });
          
          // Process each line (each line is a JSON object)
          const lines = chunk.split('\n').filter(line => line.trim() !== '');
          
          for (const line of lines) {
            try {
              const data = JSON.parse(line);
              
              if (data.message && data.message.content) {
                // For streaming, we get partial content
                let content = data.message.content;
                
                // Filter out thinking text if it appears at the start
                // Only filter on the first chunks when fullResponse is still short
                if (fullResponse.length < 500) {
                  const beforeFilter = fullResponse + content;
                  const afterFilter = filterThinkingText(beforeFilter);
                  
                  // If filtering removed text, adjust the content
                  if (afterFilter.length < beforeFilter.length) {
                    const removedLength = beforeFilter.length - afterFilter.length;
                    const alreadyProcessed = fullResponse.length;
                    
                    if (removedLength > alreadyProcessed) {
                      // Some or all of the thinking text is in this chunk
                      const toRemoveFromChunk = removedLength - alreadyProcessed;
                      content = content.substring(toRemoveFromChunk);
                      // Reset fullResponse to the filtered version
                      fullResponse = afterFilter.substring(0, alreadyProcessed);
                    }
                  }
                }
                
                // Only stream if there's content left after filtering
                if (content) {
                  onStreamUpdate(content, data);
                  fullResponse += content;
                }
              }
            } catch (e) {
              console.error('Error parsing JSON from stream:', e, line);
            }
          }
        }
      } catch (error: any) {
        // Check if this is a cancellation error
        if (error.message === 'User cancelled the response') {
          console.log('Stream was cancelled by user');
          const tokensReceived = tokenCountingService.countTokens(fullResponse);
          console.log(`📥 Tokens received from LLM: ${tokensReceived} (cancelled)`);
          return { response: fullResponse, tokensSent, tokensReceived };
        }
        console.error('Error reading stream:', error);
        throw error;
      } finally {
        currentReader = null;
      }
      
      // Calculate tokens received and return complete object
      const tokensReceived = tokenCountingService.countTokens(fullResponse);
      console.log(`📥 Tokens received from LLM: ${tokensReceived}`);
      return { response: fullResponse, tokensSent, tokensReceived };
    } else {
      // Non-streaming mode (fallback)
      // Prepare the request payload
      const payload: any = {
        model: modelId,
        messages: finalMessages,
        stream: false,
        keep_alive: -1, // Keep model loaded in RAM indefinitely
        options: effectiveOptions, // GPU/CPU split left entirely to Ollama
      };
      
      // Log the number of images being sent (now included in the messages)
      if (imageAttachments.length > 0) {
        console.log(`Request includes ${imageAttachments.length} images in the messages`);
      }
      
      // Log the complete payload with messages containing images
      
      const response = await api.post(endpoint, payload, {
        headers: getHeaders(),
      });
      
      
      if (response.data && response.data.message) {
        // Filter out thinking text from non-streaming responses too
        const filteredContent = filterThinkingText(response.data.message.content);
        const tokensReceived = tokenCountingService.countTokens(filteredContent);
        console.log(`📥 Tokens received from LLM: ${tokensReceived} (non-streaming)`);
        return { response: filteredContent, tokensSent, tokensReceived: 0 };
      }
    }
    
    return { response: 'No response from the model. Please check the Ollama API is running correctly.', tokensSent, tokensReceived: 0 };
  } catch (error: any) {
    console.error('Error sending message to Ollama API:', error);
    
    // Provide more detailed error information
    let errorMessage = 'Error: Failed to get a response from the model.';
    
    if (error.response) {
      // The request was made and the server responded with a status code
      // that falls out of the range of 2xx
      errorMessage += ` Server responded with status ${error.response.status}: ${JSON.stringify(error.response.data)}`;
      console.error('Error response data:', error.response.data);
      console.error('Error response status:', error.response.status);
      console.error('Error response headers:', error.response.headers);
    } else if (error.request) {
      // The request was made but no response was received
      errorMessage += ' No response received from server. Check if Ollama is running.';
      console.error('Error request:', error.request);
    } else {
      // Something happened in setting up the request that triggered an Error
      errorMessage += ` ${error.message}`;
      console.error('Error message:', error.message);
    }
    
    return { response: errorMessage, tokensSent: tokensSent || 0, tokensReceived: 0 };
  }
};

// Get suggested prompts
export const getSuggestedPrompts = () => {
  return [
    {
      title: 'Tell me a fun fact',
      prompt: 'Tell me a fun fact about the Roman Empire',
      description: 'about the Roman Empire',
    },
    {
      title: 'Explain supervised machine learning.',
      prompt: 'Explain supervised machine learning. \n Specifically difference between classification and regression models in machine learning.',
      description: 'Specifically difference between classification and regression models in machine learning.',
    },
    {
      title: 'Give me ideas',
      prompt: 'Give me ideas about common tourist attractions in the world.',
      description: 'Common tourist attractions in the world.',
    },
  ];
};

// Get detailed information about a specific model
export const fetchModelDetails = async (modelName: string): Promise<any> => {
  try {
    const endpoint = '/show';
    const response = await api.post(endpoint, {
      name: modelName
    }, {
      headers: getHeaders(),
    });
    
    if (response.data) {
      return response.data;
    }
    
    return null;
  } catch (error) {
    console.error(`Error fetching details for model ${modelName}:`, error);
    return null;
  }
};

// =============================================================================
// PDF FIGURE DESCRIPTION (vision-model captioning of extracted figures)
// =============================================================================
//
// After the Python backend extracts figure regions from a PDF, we ask the
// CURRENT vision-capable model to write a short textual description of each
// figure. That description is then stored on the FileAttachment (in
// `imageMeta[].description`) and inlined into the LLM's view of the PDF on
// every subsequent turn — so even after a model switch to a text-only model,
// the model still "knows" what each figure shows.
//
// We deliberately use Ollama's /api/generate (single-shot) instead of /api/chat
// to keep this call cheap and stateless — we only need one short reply per
// image, no chat history.

export interface DescribePdfImageOptions {
  /** PDF page number the figure appears on (used in the prompt). */
  page?: number;
  /** Human-readable label parsed from the caption (e.g. "Figure 3"). */
  label?: string | null;
  /** Caption text exactly as it appears in the PDF, if any. */
  caption?: string | null;
  /** Abort signal so the caller can cancel a long-running description. */
  signal?: AbortSignal;
  /** Override the per-call timeout (ms). Defaults to 60_000. */
  timeoutMs?: number;
}

/**
 * Ask `modelId` to describe a single PDF figure given as a data URI or raw
 * base64. Returns a short (1–3 sentence) description string, or `null` on
 * failure / abort. Does NOT throw — failure is non-fatal so PDF upload
 * doesn't break when the model is slow or unavailable.
 *
 * The CALLER is responsible for ensuring `modelId` actually supports vision
 * (via the `capabilities` field from /api/show). When the user's current
 * model is text-only this function should not be called at all.
 */
export const describePdfImage = async (
  modelId: string,
  imageDataOrUri: string,
  opts: DescribePdfImageOptions = {},
): Promise<string | null> => {
  if (!modelId || !imageDataOrUri) return null;
  // Ollama expects raw base64 (no data: prefix) in the `images` array.
  const cleanBase64 = imageDataOrUri.includes(',')
    ? imageDataOrUri.split(',')[1]
    : imageDataOrUri;
  if (!cleanBase64) return null;

  // Build a tight prompt: we give the model the caption (when present) so it
  // anchors the description to what the author called it, but we ask for an
  // independent visual summary it could write WITHOUT the caption. The
  // resulting text is what a text-only LLM downstream will read instead of
  // the actual pixels, so it needs to be self-contained.
  const pageStr = opts.page != null ? ` (page ${opts.page})` : '';
  const labelStr = opts.label ? `“${opts.label}”` : 'this figure';
  const captionLine = opts.caption
    ? `\nThe PDF caption for this figure is: "${opts.caption}".`
    : '';
  const prompt =
    `You are describing a single figure extracted from a PDF document so that` +
    ` a text-only language model can later answer questions about it without` +
    ` seeing the image.\n\n` +
    `Write a concise, factual description of ${labelStr}${pageStr} in 2–4` +
    ` sentences. Cover:\n` +
    `  • What KIND of visual it is (chart, diagram, photo, schematic, table-like,` +
    ` micrograph, plot, equation, etc.).\n` +
    `  • The main subject / what is being shown.\n` +
    `  • Any axes, labels, panels, legends, units, comparisons or trends you can` +
    ` actually read in the image.\n` +
    `  • Notable colors, groupings, or visual structure that would matter for` +
    ` interpreting the figure.\n` +
    `Avoid speculating beyond what is visible. Do NOT repeat the caption` +
    ` verbatim. Reply with the description only — no preamble, no markdown` +
    ` headers, no bullet points.` +
    captionLine;

  // Per-image timeout. We default to 5 minutes because the FIRST call for
  // a session also has to load the vision model into VRAM (cold start can
  // be 30–60 s on its own for 12B–27B class models). Subsequent calls are
  // much faster. The caller can override via opts.timeoutMs.
  const timeoutMs = opts.timeoutMs ?? 300_000;
  const controller = new AbortController();
  // Chain external abort signal into our own controller.
  if (opts.signal) {
    if (opts.signal.aborted) return null;
    opts.signal.addEventListener('abort', () => controller.abort(), { once: true });
  }
  const timer = setTimeout(() => controller.abort(), timeoutMs);

  const t0 = (typeof performance !== 'undefined' ? performance.now() : Date.now());
  console.info(
    `[describePdfImage] → POST /generate model=${modelId} ` +
    `page=${opts.page ?? '?'} label=${opts.label ?? 'none'} ` +
    `imgBytes≈${Math.round((cleanBase64.length * 3) / 4)} ` +
    `(timeout=${timeoutMs}ms)`,
  );

  try {
    const response = await api.post(
      '/generate',
      {
        model: modelId,
        prompt,
        images: [cleanBase64],
        stream: false,
        // Keep the reply short — we want ~80–150 tokens.
        options: {
          num_predict: 220,
          temperature: 0.2,
        },
        // Keep the model resident between figures so we don't reload weights
        // 9× in a row for a 9-figure paper.
        keep_alive: '10m',
      },
      {
        headers: getHeaders(),
        signal: controller.signal,
        // Axios timeout as a backup; the AbortController is primary.
        timeout: timeoutMs + 5_000,
      },
    );
    const dt = Math.round(((typeof performance !== 'undefined' ? performance.now() : Date.now()) - t0));
    const text: string | undefined = response?.data?.response;
    const evalCount = response?.data?.eval_count;
    const totalDuration = response?.data?.total_duration;
    console.info(
      `[describePdfImage] ← ${dt}ms model=${modelId} ` +
      `status=${response?.status} eval_count=${evalCount ?? '?'} ` +
      `total_duration=${totalDuration ?? '?'} ` +
      `bytes=${text ? text.length : 0}`,
    );
    if (!text) {
      console.warn(`[describePdfImage] empty response.response from ${modelId}`, response?.data);
      return null;
    }
    // Strip surrounding whitespace and any accidental "Description:" prefix.
    const cleaned = text
      .trim()
      .replace(/^(description|figure description|summary)\s*:\s*/i, '')
      .trim();
    return cleaned || null;
  } catch (err: any) {
    const dt = Math.round(((typeof performance !== 'undefined' ? performance.now() : Date.now()) - t0));
    if (controller.signal.aborted) {
      console.warn(
        `[describePdfImage] aborted/timeout after ${dt}ms for model ${modelId}`,
      );
    } else {
      // Surface as much detail as axios gives us so the user can see
      // whether the call hit Ollama at all (network/CORS/404 vs 500).
      const status = err?.response?.status;
      const respData = err?.response?.data;
      console.error(
        `[describePdfImage] failed after ${dt}ms for model ${modelId}: ` +
        `status=${status ?? 'no-response'} message=${err?.message || err}`,
        respData ?? '',
      );
    }
    return null;
  } finally {
    clearTimeout(timer);
  }
};



// Export the api instance for use in other services
export { api as ollamaApi };

export default api;

