export interface ModelType {
  id: string;
  name: string;
  description?: string;
  parameters?: Record<string, any>;
  size?: number; // On-disk size in bytes, as reported by Ollama's /api/tags
  quantization?: string;
  isDefault?: boolean;
}

/**
 * Per-image metadata produced for each figure/table region extracted from a
 * PDF. The base64 image payload itself lives in `FileAttachment.images[i]`
 * (so the existing pipeline that forwards images to vision LLMs keeps
 * working unchanged); this struct sits at `FileAttachment.imageMeta[i]` and
 * is what gives a TEXT-only LLM enough context to reason about each figure.
 *
 * The crucial field is `description` — a 1–3 sentence summary of the figure
 * generated by sending the image to the user's currently-selected vision
 * model right after PDF extraction. We persist it into `chats.json` so the
 * description is available on every subsequent turn, even after a model
 * switch or app reload (no need to re-describe).
 *
 * All other fields come straight from the backend extractor and are also
 * persisted, giving the LLM a complete profile of where each figure lives
 * in the document and how the author labeled it.
 */
export interface PdfImageMeta {
  /** 1-based index across the whole document (matches the backend). */
  index: number;
  /** PDF page the figure appears on (1-based). */
  page: number;
  /** Human-readable label parsed from the caption (e.g. "Figure 3",
   *  "Extended Data Figure 1", "Table 2"). May be undefined when no
   *  recognizable caption was found (e.g. non-English papers). */
  label?: string | null;
  /** Full caption text exactly as it appears in the PDF, if found. */
  caption?: string | null;
  /** Figure region bbox in PDF user-space points: [x0, y0, x1, y1]. */
  bbox?: [number, number, number, number] | null;
  /** Pixel dimensions of the rendered crop. */
  width?: number;
  height?: number;
  /** "jpeg" | "png" — matches `images[i]` data URI. */
  format?: string;
  /**
   * AI-generated description of the figure produced by sending the image
   * to a vision LLM. 1–3 sentences. Undefined when description failed or
   * the user's current model isn't vision-capable.
   */
  description?: string;
  /** Model id used to generate `description` (e.g. "gemma3:latest"). */
  describedBy?: string;
  /** ISO timestamp of when `description` was produced. */
  describedAt?: string;
}

export interface FileAttachment {
  id: string;
  name: string;
  type: 'text' | 'image' | 'document' | 'pdf' | 'audio'; // Added 'pdf' type
  content?: string; // For text files, we'll store the content directly
  images?: string[]; // Array of image data URLs for PDFs with images
  /**
   * Parallel array to `images`: rich per-image metadata (label, caption,
   * page, bbox, dimensions, AI-generated description). Length matches
   * `images.length` when both are present, but `imageMeta` may also exist
   * WITHOUT `images` (e.g. text-only models — we still persist the textual
   * descriptions so the LLM has context for the document's figures even
   * though the base64 image bytes were intentionally stripped to save
   * tokens). Order is document order (page-then-position).
   */
  imageMeta?: PdfImageMeta[];
  url?: string;     // For future use with other file types
  size: number;
  timestamp: string;
}


export interface MessageType {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: string;
  attachments?: FileAttachment[]; // Add support for file attachments
  tokenCount?: number; // Track individual message tokens
  contextTokensUsed?: number; // Track total context tokens sent to LLM for this message
}

export interface ChatType {
  id: string;
  title: string;
  modelId: string;
  messages: MessageType[];
  createdAt: string;
  updatedAt?: string;
  tokenStats?: {
    totalTokensSent: number;
    totalTokensReceived: number;
    contextLength: number;
    lastUpdated: string;
  };
}

export interface SuggestedPrompt {
  title: string;
  prompt: string;
  description?: string;
}
